# Author: Janusz Lewandowski <lew21@xtreeme.org>
# Contributor: David McFarland <corngood@gmail.com>
# Maintainer: Andrew Shark <ashark @at@ linuxcomp.ru>
# Autogenerated from AMD's Packages file

major=20.40
minor=1147286
ubuntu_ver=20.04

#pkgbase=amdgpu-pro-installer
pkgname=amdgpu-pro
pkgver=${major}_${minor}
pkgrel=1
arch=('x86_64')
url='https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-40'
license=('custom: multiple')
groups=('Radeon_Software_for_Linux')
makedepends=('wget')

DLAGENTS='https::/usr/bin/wget --referer https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-40 -N %u'

source=(https://drivers.amd.com/drivers/linux/amdgpu-pro-${major}-${minor}-ubuntu-20.04.tar.xz)
sha256sums=(e6b2b2d76cc80ca989b5f2f1cf3e0c0bd0bdee97b1dba0767c28c91995cffb5e)

PKGEXT=".pkg.tar"

# Extract all files at once ( quicker, easier to maintain )
extract-all() {
	local current="`pwd`"	
	rm -rf amdgpu-pro 
	mkdir -p amdgpu-pro
	cd amdgpu-pro
	for d in `ls $current/amdgpu-pro-${major}-${minor}-ubuntu-20.04/*.deb`
	do
		ar x "$d"
		tar -C $current/../pkg/amdgpu-pro -xf data.tar.xz	
	done
	cd $current
}

# extracts a debian package
# $1: deb file to extract

# move ubuntu specific /usr/lib/x86_64-linux-gnu to /usr/lib
# $1: debian package library dir (goes from opt/amdgpu or opt/amdgpu-pro and from x86_64 or i386)
# $2: arch package library dir (goes to usr/lib or usr/lib32)
move_libdir() {
    local deb_libdir="$1"
    local arch_libdir="$2"

    if [ -d "${pkgdir}/${deb_libdir}" ]; then
        if [ ! -d "${pkgdir}/${arch_libdir}" ]; then
            mkdir -p "${pkgdir}/${arch_libdir}"
        fi
        mv -t "${pkgdir}/${arch_libdir}/" "${pkgdir}/${deb_libdir}"/*
        find ${pkgdir} -type d -empty -delete
    fi
}

package() {
    pkgdesc="AMDGPU-PRO Drivers"
    license=('MIT')
    arch=('any')
	extract-all
}

